<start>        ::= <triple><triple><triple><triple><triples>
<triples>      ::= <triple> | <triple> <triples>
<triple>       ::= <defTriple> | <parTriple>
<defTriple>    ::= <IRI>" a " <class> ".\n"
<parTriple>    ::= <IRI>" :parentOf " <IRI> ".\n"
<class>        ::= ":Father" | ":Mother" | ":Person" | "owl:NamedIndividual"
<IRI>          ::= <IRIREF> #<PREFIXEDNAME>                             #| <IRIREF>
#<PREFIXEDNAME> ::= <PNAME_LN>                                 #| <PNAME_NS>
<IRIREF>       ::= "<a>" | "<b>" | "<c>" | "<d>" | "<e>"
#<PNAME_NS>     ::= "p1:" | "p2:"
#<PNAME_LN>     ::= <PNAME_NS> "c" | <PNAME_NS> "d"
