PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rr: <http://www.w3.org/ns/r2rml#>
PREFIX rml: <http://semweb.mmlab.be/ns/rml#> # current one still in use
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

# based on LINE 91 of change_data.nt (<http://epo-changes.org/3.0.0-3.0.1/AddClass/epo%3AConcessionEstimate> rdf:type omv:AddClass .)


ASK {
    epo:class1 rdf:type rr:TriplesMap.
    epo:class1 rml:logicalSource ?logicalSource .
    ?logicalSource rml:source "XXXX" . #this is not wrong, are referneces to data that will be changed by the knowledge engineer manually
    ?logicalSource rml:referenceFormularion "XXXX" .
    epo:class1 rr:subjectMap ?subjectMap .
    ?subjectMap rr:class epo:class1 .
    ?subjectMap rr:template "XXXX"
}